### PR TITLE
Make GUI match top screen color filter

### PR DESCRIPTION
**Pull request by JeffRuLz**
This edit makes the color filter option also change the GUI color on the bottom screen.

### CODE REVIEW

**Comment by queenbiscuit311** [comment]
Just tested this out, seems to work with no issues.

**Comment by pmsobrado** [comment]
Will this be included in next stable build? As an option or by default and no-removable feature?

**Comment by skyfloogle** [comment]
I felt this looked better enough to just enable by default.

**Comment by pmsobrado** [comment]
OK then :)

**Pull request merged**
